### ISSUE TITLE
 No such file or directory: 'output/HumanoidIm/pulse_vae_iclr/Humanoid.pth'

### ISSUE THREAD

**Issue by PB21000283** [SMPLOlympics/SMPLOlympics#11]
**Hello,**

**I ran the following code again:**
export OMP_NUM_THREADS=1
python phc/run_hydra.py \
    project_name=SMPLOlympics num_agents=1 \
    learning=pulse exp_name=longjump_pulse  \
    env=env_amp_z_longjump env.num_envs=2048 env.task=HumanoidLongjumpZ env.enableTaskObs=True \
    robot=smpl_humanoid  robot.has_upright_start=True  \
    env.motion_file=./sample_data/amass_isaac_simple_run_upright_slim.pkl \
    headless=True env.stateInit=Default env.episode_length=600 learning.params.config.max_epochs=100000
**and encountered an error. The message indicated:**
Waiting 1 before trying again...
Exception [Errno 2] No such file or directory: 'output/HumanoidIm/pulse_vae_iclr/Humanoid.pth' when trying to execute <function load at 0x737626f0d1f0> with args:('output/HumanoidIm/pulse_vae_iclr/Humanoid.pth',) and kwargs:{}...
Waiting 2 before trying again...
Exception [Errno 2] No such file or directory: 'output/HumanoidIm/pulse_vae_iclr/Humanoid.pth' when trying to execute <function load at 0x737626f0d1f0> with args:('output/HumanoidIm/pulse_vae_iclr/Humanoid.pth',) and kwargs:{}...
Waiting 4 before trying again...
Exception [Errno 2] No such file or directory: 'output/HumanoidIm/pulse_vae_iclr/Humanoid.pth' when trying to execute <function load at 0x737626f0d1f0> with args:('output/HumanoidIm/pulse_vae_iclr/Humanoid.pth',) and kwargs:{}...
Waiting 8 before trying again...
Exception [Errno 2] No such file or directory: 'output/HumanoidIm/pulse_vae_iclr/Humanoid.pth' when trying to execute <function load at 0x737626f0d1f0> with args:('output/HumanoidIm/pulse_vae_iclr/Humanoid.pth',) and kwargs:{}...
Waiting 16 before trying again...
**It suggests a missing file. The code used is a version from a month ago. Could you please clarify what might be causing this issue? Thank you very much.**

**Comment by PB21000283** [comment]
**And I encountered an error when running the following code:**
python phc/run_hydra.py \
    project_name=SMPLOlympics num_agents=1 \
    learning=ppo exp_name=highjump_ppo  \
    env=env_amp_z env.num_envs=2048 env.task=HumanoidHighjump env.enableTaskObs=True \
    robot=smpl_humanoid  robot.has_upright_start=True  \
    env.motion_file=./sample_data/amass_isaac_simple_run_upright_slim.pkl headless=True env.stateInit=Default \
    env.episode_length=300 learning.params.config.max_epochs=20000 no_virtual_display=False epoch=-1 test=True env.num_envs=1  headless=False
**The error was:** 
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
**Additionally, the Xephyr display is also black. Could you please advise what might be causing this? Thank you very much!**

**Comment by ZhengyiLuo** [comment]
My bad, I renamed the directory to `pulse_vae` and haven't fixed all the commands. It has now been fixed; please run bash_download again.

**Comment by ZhengyiLuo** [comment]
> **And I encountered an error when running the following code:** python phc/run_hydra.py project_name=SMPLOlympics num_agents=1 learning=ppo exp_name=highjump_ppo env=env_amp_z env.num_envs=2048 env.task=HumanoidHighjump env.enableTaskObs=True robot=smpl_humanoid robot.has_upright_start=True env.motion_file=./sample_data/amass_isaac_simple_run_upright_slim.pkl headless=True env.stateInit=Default env.episode_length=300 learning.params.config.max_epochs=20000 no_virtual_display=False epoch=-1 test=True env.num_envs=1 headless=False **The error was:** RuntimeError: CUDA error: device-side assert triggered CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. **Additionally, the Xephyr display is also black. Could you please advise what might be causing this? Thank you very much!**

Please try running with GPU 0 and `no_virtual_display=True`.

**Comment by PB21000283** [comment]
**Hello! After running the modified download command, I am still encountering the following error:**
 Exception [Errno 2] No such file or directory: 'output/HumanoidIm/pulse_vae_iclr/Humanoid.pth' when trying to execute <function load at 0x7f1e9954a1f0> with args:('output/HumanoidIm/pulse_vae_iclr/Humanoid.pth',) and kwargs:{}.
 **The code is still the version from a month ago. Although the folder pulse_vae_iclr exists, the filenames inside are incorrect; in fact, the names of the downloaded data files are all blank. Should I rename the downloaded data file to Humanoid.pth? Do the other data files need to be renamed as well?** 
**Additionally, after using** no_virtual_display=True **and** gpu=0, **the code can evaluate normally but cannot display the robot's visualized movements. How can I view the coordinated movements of the robot after training? Thank you very much!**

**Comment by ZhengyiLuo** [comment]
> **Hello! After running the modified download command, I am still encountering the following error:** Exception [Errno 2] No such file or directory: 'output/HumanoidIm/pulse_vae_iclr/Humanoid.pth' when trying to execute <function load at 0x7f1e9954a1f0> with args:('output/HumanoidIm/pulse_vae_iclr/Humanoid.pth',) and kwargs:{}. **The code is still the version from a month ago. Although the folder pulse_vae_iclr exists, the filenames inside are incorrect; in fact, the names of the downloaded data files are all blank. Should I rename the downloaded data file to Humanoid.pth? Do the other data files need to be renamed as well?** **Additionally, after using** no_virtual_display=True **and** gpu=0, **the code can evaluate normally but cannot display the robot's visualized movements. How can I view the coordinated movements of the robot after training? Thank you very much!**

Try pulling the newest code and upgrade gdown `pip install gdown --upgrade`.

**Comment by PB21000283** [comment]
**Hello, I am still encountering the exact same two issues as before, even after using the latest version of the code. Thank you.**

**Comment by PB21000283** [comment]
**Hello, I renamed the downloaded file to** Humanoid.pth, **
** python phc/run_hydra.py \ project_name=SMPLOlympics num_agents=1 \ learning=pulse exp_name=highjump_pulse \ env=env_amp_z env.num_envs=2048 env.task=HumanoidHighjumpZ env.enableTaskObs=True \ robot=smpl_humanoid robot.has_upright_start=True \ env.motion_file=./sample_data/amass_isaac_simple_run_upright_slim.pkl headless=True env.stateInit=Default \ env.episode_length=300 learning.params.config.max_epochs=20000 **is running smoothly.** **However, after using** no_virtual_display=True and gpu=0, **the code can evaluate normally but cannot display the robot's visualized movements because the virtual screen is not launched. How can I view the visualized movements to check if they are coordinated after the training? Thank you very much!**

**Comment by ZhengyiLuo** [comment]
The `no_virtual_dispaly=True` is disabling a display utils I use to capture the viewer and instead uses the default IsaacGym viewer. Does IsaacGym runs normally for you on your end? Have you tried some of the samples from its python directory?
