### ISSUE TITLE
Video saving

### ISSUE THREAD

**Issue by he-nantian** [SMPLOlympics/SMPLOlympics#12]
Wonderful work! I wonder how to save visually intuitive videos during training or evaluation period. Is there any arguments to realize this function?

**Comment by tesslerc** [comment]
### Recording motions from a **trained** model:
During inference you can press "L" to start recording and "L" again to stop (and it will then save the video). However, this This requires running with with rendering turned on (headless=False).

### Recording motions **during training**:
Training with headless=False is very slow (rendering is expensive).
What you could do in this case is:
1. During training you periodically record an episode. This is the humanoid state and scene information.
2. Offline, you can then load the saved data and visualize.
- One way is to load the data back into Isaac and kinematically replay the scene.
- An alternative is to directly render the motion. For example InterScene provide an example with the SAMP dataset: https://github.com/IDC-Flash/InterScene/blob/main/InterScene/data/dataset_samp_sit/generate_motion.py
