### ISSUE TITLE
Success Rate in Table 1

### ISSUE THREAD

**Issue by he-nantian** [SMPLOlympics/SMPLOlympics#14]
I wonder the implementation detail of the Suc Rate metric in Table 1 since I have not found it in the manuscript.
<img width="1238" alt="image" src="https://github.com/user-attachments/assets/a4501d54-201c-416e-9c48-cda92f8267c8">

**Comment by ZhengyiLuo** [comment]
Success rate is quite straight forward for these sports: no termination based on the rules. Essentially, if the episode ends without terminating (e.g. not clearing the high jump bar) then it is no longer successful.
