### ISSUE TITLE
Very amazing work! Do you have plans to test on real-world robots?

### ISSUE THREAD

**Issue by sjtuyinjie** [SMPLOlympics/SMPLOlympics#2]
Very amazing work! Shocked by your performance on such complex RL tasks. Do you have plans to test on real-world robots? I'm curious about the possibility of learning from internet videos for deploying real humanoid robots.

**Comment by ZhengyiLuo** [comment]
Yes! We have already had some success transferring from [PHC](https://www.zhengyiluo.com/PHC-Site/) to [OmniH2O](https://omni.human2humanoid.com/), and we hope similar pipeline could work for the real robot as well.
