### ISSUE TITLE
How to download motion data in the 'sample_data/' dir?

### ISSUE THREAD

**Issue by YHQpkueecs** [SMPLOlympics/SMPLOlympics#3]
Hi! When I run the scripts for ppo for different tasks, an error always occurs:
```
File "/home/xxx/SMPLOlympics/phc/utils/motion_lib_base.py", line 123, in __init__
    self.load_data(self.m_cfg.motion_file,  min_length = self.m_cfg.min_length, im_eval = self.m_cfg.im_eval)
  File "/home/xxx/SMPLOlympics/phc/utils/motion_lib_base.py", line 158, in load_data
    self._motion_data_load = joblib.load(self._motion_data_load[0]) # set self._motion_data_load to a sample of the data
IndexError: list index out of range
```
I checked that `self._motion_data_load` is loaded from some missing files in `sampled_data/`. For example, when I run `bash scripts/run_boxing.sh`, it tries to load `./sample_data/video_boxing_afterproc_upright.pkl`. But after I download everything following readme, I cannot find this file.

**Comment by ZhengyiLuo** [comment]
All data are now released, download using the `download_data.sh` script.  Thanks!
