### ISSUE TITLE
Error Encountered in `run_boxing.sh`: Missing `model_builder` Attribute in `Runner` Class

### ISSUE THREAD

**Issue by tobeybyte** [SMPLOlympics/SMPLOlympics#5]
When I executed the `run_boxing.sh` file, I encountered an error:

```
Traceback (most recent call last):
  File "phc/run_hydra.py", line 365, in main
    runner = build_alg_runner(algo_observer)
  File "phc/run_hydra.py", line 270, in build_alg_runner
    runner.model_builder.model_factory.register_builder('amp', lambda network, **kwargs: amp_models.ModelAMPContinuous(network))
AttributeError: 'Runner' object has no attribute 'model_builder'
```

I checked the `rl_games` library (including versions 1.6.1, 1.6.0, 1.5.2, 1.5.1, 1.5.0, 1.4.0) and found that the `Runner` class does not have the `model_builder` attribute. Did you modify the library code?

**Comment by ZhengyiLuo** [comment]
`pip install -r requirement.txt` should install `rl-games==1.1.4`. 

Sorry I used an older version of rl-games and hasn't had the chance to upgrade it.

**Comment by tobeybyte** [comment]
Thank you very much for your help. I wish you success in your work.

ZhengyiLuo ***@***.***> 于2024年8月4日周日 05:10写道：
