### ISSUE TITLE
Problems about vis_smplx_mano_o3d.py in scripts /vis/

### ISSUE THREAD

**Issue by lala1910** [SMPLOlympics/SMPLOlympics#7]
Thanks for sharing your work，I tried to run ` vis_smplx_mano_o3d.py`and met the error
![截图 2024-08-03 10-12-06](https://github.com/user-attachments/assets/d3230c88-11f3-4a33-acd8-1a8143d7cf9b)
Could you please tell me how to prepare this` test.pkl`? I've modified the code trying to only visualize hand

**Comment by ZhengyiLuo** [comment]
Hi! This script is for visualizing [interhand data](https://mks0601.github.io/ReInterHand/) together with SMPL-X for visualization and is not required to run any code for SMPLOlypmics. I will go ahead and remove this script as it is for another project.
